from python.helpers.api import ApiHandler, Request, Response

import asyncio
import json
import os
import shutil
import sys
from pathlib import Path

_plugin_root = Path(__file__).parent.parent
if str(_plugin_root) not in sys.path:
    sys.path.insert(0, str(_plugin_root))
from python.helpers import plugins

_CE_REPO_URL = "https://github.com/Context-Engine-AI/Context-Engine.git"
_DEFAULT_REPO_PATH = os.path.expanduser("~/.context-engine/repo")

# Minimal .env content for Agent Zero integration.
# Uses the shared embedding service, Redis state backend, and
# sensible defaults that match the plugin's default_config.yaml.
_ENV_TEMPLATE = """\
# Generated by Agent Zero Context Engine plugin
QDRANT_URL=http://qdrant:6333
COLLECTION_NAME={collection_name}
EMBEDDING_MODEL=nomic-ai/nomic-embed-text-v1.5
EMBEDDING_PROVIDER=remote
EMBEDDING_SERVICE_URL=http://embedding:8100
CODEBASE_STATE_BACKEND=redis
CODEBASE_STATE_REDIS_URL=redis://redis:6379/0
FASTMCP_HOST=0.0.0.0
FASTMCP_PORT=8000
FASTMCP_INDEXER_PORT=8001
FASTMCP_TRANSPORT=sse
FASTMCP_HTTP_TRANSPORT=streamable-http
FASTMCP_HTTP_PORT=8002
FASTMCP_INDEXER_HTTP_PORT=8003
HOST_INDEX_PATH={host_index_path}
"""


class DockerHandler(ApiHandler):
    """Docker Compose lifecycle handler for the Context Engine stack.

    Manages cloning the Context Engine repository, generating the .env
    configuration, and running docker compose against the real repo.
    """

    async def process(self, input: dict, request: Request) -> dict | Response:
        try:
            action = input.get("action", "").strip().lower()

            if action not in ("up", "down", "ps"):
                return {
                    "ok": False,
                    "error": "Invalid action. Use 'up', 'down', or 'ps'.",
                }

            config = plugins.get_plugin_config("context-engine")
            repo_path = Path(os.path.expanduser(
                config.get("context_engine_repo_path", _DEFAULT_REPO_PATH)
            ))
            compose_file = repo_path / "docker-compose.yml"

            if action == "up":
                return await self._up(repo_path, compose_file, config)
            elif action == "down":
                return await self._down(compose_file)
            else:
                return await self._ps(compose_file)
        except Exception as e:
            return {"ok": False, "error": str(e)}

    # ------------------------------------------------------------------
    # Actions
    # ------------------------------------------------------------------

    async def _up(self, repo_path: Path, compose_file: Path, config: dict) -> dict:
        # Step 1: Clone repo if missing
        if not compose_file.is_file():
            clone_result = await self._ensure_repo(repo_path)
            if not clone_result["ok"]:
                return clone_result

        # Step 2: Generate .env if missing
        env_file = repo_path / ".env"
        if not env_file.is_file():
            self._generate_env(env_file, config)

        # Step 3: docker compose up -d (builds images on first run)
        return await self._run_compose(compose_file, ["up", "-d", "--build"], timeout=600)

    async def _down(self, compose_file: Path) -> dict:
        if not compose_file.is_file():
            return {"ok": False, "error": "Context Engine is not installed. Toggle Deploy to clone and build."}
        return await self._run_compose(compose_file, ["down"], timeout=60)

    async def _ps(self, compose_file: Path) -> dict:
        if not compose_file.is_file():
            return {
                "ok": True,
                "running": False,
                "services": [],
                "service_count": 0,
                "running_count": 0,
                "installed": False,
            }

        try:
            proc = await asyncio.create_subprocess_exec(
                "docker", "compose", "-f", str(compose_file), "ps", "--format", "json",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=str(compose_file.parent),
            )
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=30)
        except FileNotFoundError:
            return {"ok": False, "error": "Docker is not installed or not in PATH."}
        except asyncio.TimeoutError:
            try:
                proc.kill()
                await proc.wait()
            except ProcessLookupError:
                pass
            return {"ok": False, "error": "Timed out checking services."}

        if proc.returncode != 0:
            return {
                "ok": False,
                "error": stderr.decode().strip() or "docker compose ps failed",
            }

        # docker compose ps --format json: JSON array (v2.21+) or NDJSON (older).
        raw = stdout.decode().strip()
        services = []
        if raw:
            try:
                parsed = json.loads(raw)
                services = parsed if isinstance(parsed, list) else [parsed]
            except json.JSONDecodeError:
                for line in raw.splitlines():
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        services.append(json.loads(line))
                    except json.JSONDecodeError:
                        continue

        running_count = sum(1 for s in services if s.get("State") == "running")

        return {
            "ok": True,
            "running": running_count > 0 and running_count == len(services),
            "services": services,
            "service_count": len(services),
            "running_count": running_count,
            "installed": True,
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    async def _ensure_repo(self, repo_path: Path) -> dict:
        """Clone the Context Engine repository if it doesn't exist."""
        if (repo_path / "docker-compose.yml").is_file():
            return {"ok": True, "output": "Repository already present."}

        # Ensure parent directory exists
        repo_path.parent.mkdir(parents=True, exist_ok=True)

        # Check git is available
        if not shutil.which("git"):
            return {"ok": False, "error": "Git is not installed. Please install Git to use the auto-deploy feature."}

        try:
            proc = await asyncio.create_subprocess_exec(
                "git", "clone", "--depth", "1", _CE_REPO_URL, str(repo_path),
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=120)
        except asyncio.TimeoutError:
            try:
                proc.kill()
                await proc.wait()
            except ProcessLookupError:
                pass
            return {"ok": False, "error": "Cloning timed out. Check your internet connection."}

        if proc.returncode != 0:
            return {
                "ok": False,
                "error": f"Failed to clone Context Engine: {stderr.decode().strip()}",
            }

        return {"ok": True, "output": "Repository cloned successfully."}

    def _generate_env(self, env_file: Path, config: dict) -> None:
        """Generate .env from template with Agent Zero defaults."""
        collection_name = config.get("collection_name", "codebase")
        # Use current working directory as the default index path
        host_index_path = os.getcwd()

        content = _ENV_TEMPLATE.format(
            collection_name=collection_name,
            host_index_path=host_index_path,
        )
        env_file.write_text(content)

    async def _run_compose(self, compose_file: Path, args: list[str], timeout: int) -> dict:
        """Run a docker compose command against the real repo's compose file."""
        try:
            proc = await asyncio.create_subprocess_exec(
                "docker", "compose", "-f", str(compose_file), *args,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=str(compose_file.parent),
            )
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout)
        except FileNotFoundError:
            return {"ok": False, "error": "Docker is not installed or not in PATH."}
        except asyncio.TimeoutError:
            try:
                proc.kill()
                await proc.wait()
            except ProcessLookupError:
                pass
            return {
                "ok": False,
                "error": f"Command timed out after {timeout}s. First build can take several minutes.",
            }

        output = stdout.decode().strip()
        err_output = stderr.decode().strip()
        combined = "\n".join(filter(None, [output, err_output]))

        if proc.returncode != 0:
            return {
                "ok": False,
                "error": err_output or "Command failed",
                "output": combined,
            }

        return {"ok": True, "output": combined}
