export function createInboxStore() {
  return {
    items: [],
    selected: null,
    filter: 'all',
    draft: '',

    get filteredItems() {
      if (this.filter === 'all') return this.items;
      if (this.filter === 'signoff') return this.items.filter(i => i.needsSignoff);
      return this.items.filter(i => i.category === this.filter);
    },

    setFilter(f) { this.filter = f; },
    select(item) { this.selected = item; this.draft = item.draft || ''; },

    summarize() {
      if (!this.selected) return;
      // Placeholder: integrate with backend summary action
      this.selected.summary = 'Summary generated by Agent Zero: ' + (this.selected.preview || '').slice(0,140) + '...';
    },

    generateDraft() {
      if (!this.selected) return;
      const base = this.selected.type === 'lab' ? 'Your lab results show ...' : 'Thanks for your message ...';
      this.draft = `${base}\n\n— Draft prepared by Agent Zero.`;
    },

    approveAndSend() {
      if (!this.selected) return;
      // Placeholder send
      this.selected.needsSignoff = false;
      alert('Approved and sent.');
    },

    requestChanges() {
      alert('Requested changes from agent.');
    },

    init() {
      // Seed with mock data for skeleton
      this.items = [
        { id: '1', initials:'JS', subject:'Refill request: Lisinopril', patient:'John Smith', preview:'Running low, can I get a refill?', type:'refill', category:'refills', badge:'Refill', badgeClass:'refill', needsSignoff:true, body:'Hi Doc, I am almost out of Lisinopril 10mg...', nextAppt:'Aug 22 10:00', meds:'Lisinopril', allergy:'NKDA' },
        { id: '2', initials:'MB', subject:'Lab: CMP results', patient:'Mary Brown', preview:'Normal except ALT mildly elevated', type:'lab', category:'labs', badge:'Lab', badgeClass:'lab', needsSignoff:true, body:'CMP results attached...', nextAppt:'Sep 3 14:30', meds:'Metformin', allergy:'PCN' },
        { id: '3', initials:'TG', subject:'Message from cardiology', patient:'—', preview:'Colleague update about consult', type:'colleague', category:'colleagues', badge:'Colleague', badgeClass:'', needsSignoff:false, body:'We saw Mr. X and recommend ...' },
        { id: '4', initials:'AP', subject:'Patient message: cough', patient:'Ana Perez', preview:'Cough for 3 days with fever', type:'patient', category:'patients', badge:'Patient', badgeClass:'', needsSignoff:false, body:'I have had a cough ...' },
        { id: '5', initials:'AS', subject:'Appointment change', patient:'—', preview:'Rescheduled due to conflict', type:'appt', category:'appointments', badge:'Appt', badgeClass:'', needsSignoff:false, body:'Appointment moved to ...' },
      ];
    }
  }
}
